# Generated by Django 5.0.6 on 2024-06-25 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='login',
            old_name='password',
            new_name='password1',
        ),
        migrations.RenameField(
            model_name='signin',
            old_name='password2',
            new_name='password',
        ),
        migrations.RemoveField(
            model_name='signin',
            name='email',
        ),
        migrations.RemoveField(
            model_name='signin',
            name='password1',
        ),
        migrations.AddField(
            model_name='login',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AddField(
            model_name='login',
            name='password2',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
